server:
  port: ${PAYMENT_STUB_SERVER_PORT:9090}

spring:
  jpa:
    generate-ddl: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/billing}
    username: ${DATASOURCE_USERNAME:billing}
    password: ${DATASOURCE_PASSWORD:billing}

logging:
  level:
    com:
      atomikos: DEBUG
